const weaponsImages = {
    // Armory Buttons
    ASSAULT:{
        active_icon: require('../../assets/armory/button-ar-selected.png'),
        menu_icon: require('../../assets/armory/button-ar.png'),
    },
    SHOTGUN:{
        active_icon: require('../../assets/armory/button-shotgun-selected.png'),
        menu_icon: require('../../assets/armory/button-shotgun.png'),
    },
    SNIPER:{
        active_icon: require('../../assets/armory/button-sr-selected.png'),
        menu_icon: require('../../assets/armory/button-sr.png'),
    },
    PISTOL:{
        active_icon: require('../../assets/armory/button-pistol-selected.png'),
        menu_icon: require('../../assets/armory/button-pistol.png'),
    },
    LMG:{
        active_icon: require('../../assets/armory/button-lmg-selected.png'),
        menu_icon: require('../../assets/armory/button-lmg.png'),
    },
    SMG:{
        active_icon: require('../../assets/armory/button-smg-selected.png'),
        menu_icon: require('../../assets/armory/button-smg.png'),
    },
    // Assault Rifle Skins
    FLATLINE:{
        // Default Skin
        factory: require('../../assets/armory/assault-rifles/flatline-factory-issue.png'),
        // Legendary Skins
        supernova: require('../../assets/armory/assault-rifles/flatline-supernova.png'),
        hazardPay: require('../../assets/armory/assault-rifles/flatline-hazard-pay.png'),
        theSpineChiller: require('../../assets/armory/assault-rifles/flatline-the-spine-chiller.png'),
        theLowrider: require('../../assets/armory/assault-rifles/flatline-the-lowrider.png'),
        // Epic Skins
        storm: require('../../assets/armory/assault-rifles/flatline-eye-of-the-storm.png'),
        trial: require('../../assets/armory/assault-rifles/flatline-trial-by-fire.png'),
        honor: require('../../assets/armory/assault-rifles/flatline-code-of-honor.png'),
        grid: require('../../assets/armory/assault-rifles/flatline-off-the-grid.png'),
        enemy: require('../../assets/armory/assault-rifles/flatline-break-the-enemy.png'),
        // Rare Skins
        generation: require('../../assets/armory/assault-rifles/flatline-generation-x.png'),
        outback: require('../../assets/armory/assault-rifles/flatline-outback.png'),
        sweet: require('../../assets/armory/assault-rifles/flatline-sweet-16.png'),
        fusion: require('../../assets/armory/assault-rifles/flatline-cold-fusion.png'),
        shattered: require('../../assets/armory/assault-rifles/flatline-shattered.png'),
        stellar: require('../../assets/armory/assault-rifles/flatline-stellar.png'),
        jungle: require('../../assets/armory/assault-rifles/flatline-jungle-frenzy.png'),
        cloudburst: require('../../assets/armory/assault-rifles/flatline-cloudburst.png'),
        yellow: require('../../assets/armory/assault-rifles/flatline-yellow-snake.png'),
        skyrise: require('../../assets/armory/assault-rifles/flatline-skyrise.png'),
        jester: require('../../assets/armory/assault-rifles/flatline-jester.png'),
        derez: require('../../assets/armory/assault-rifles/flatline-derez.png'),
        chaos: require('../../assets/armory/assault-rifles/flatline-chaos-theory.png'),
        triumphant: require('../../assets/armory/assault-rifles/flatline-triumphant-arch.png'),
        newmoon: require('../../assets/armory/assault-rifles/flatline-new-moon.png'),
        // Common Skins
        midnight: require('../../assets/armory/assault-rifles/flatline-midnight.png'),
        cardinal: require('../../assets/armory/assault-rifles/flatline-cardinal.png'),
        artic: require('../../assets/armory/assault-rifles/flatline-artic.png'),
        sunfire: require('../../assets/armory/assault-rifles/flatline-sunfire.png'),
        clearwater: require('../../assets/armory/assault-rifles/flatline-clearwater.png'),
        flamingo: require('../../assets/armory/assault-rifles/flatline-flamingo.png'),
        sandstorm: require('../../assets/armory/assault-rifles/flatline-sandstorm.png'),
        rainforest: require('../../assets/armory/assault-rifles/flatline-rainforest.png'),
        evergreen: require('../../assets/armory/assault-rifles/flatline-evergreen.png'),
        orchid: require('../../assets/armory/assault-rifles/flatline-orchid.png'),
        bengal: require('../../assets/armory/assault-rifles/flatline-bengal.png'),
        yellowjacket: require('../../assets/armory/assault-rifles/flatline-yellowjacket.png'),
        lagoon: require('../../assets/armory/assault-rifles/flatline-lagoon.png'),
        clover: require('../../assets/armory/assault-rifles/flatline-clover.png'),
        oceanic: require('../../assets/armory/assault-rifles/flatline-oceanic.png'),
    },
    HEMLOK:{
        // Default Skin
        factory: require('../../assets/armory/assault-rifles/hemlock-factory-issue.png'),
        // Legendary Skins
        theGloriousOne: require('../../assets/armory/assault-rifles/hemlock-the-glorious-one.png'),
        lostQueen: require('../../assets/armory/assault-rifles/hemlock-lost-queen.png'),
        pressurePoint: require('../../assets/armory/assault-rifles/hemlock-pressure-point.png'),
        fluidMechanics: require('../../assets/armory/assault-rifles/hemlock-fluid-mechanics.png'),
        // Epic Skins
        storm: require('../../assets/armory/assault-rifles/hemlock-eye-of-the-storm.png'),
        trial: require('../../assets/armory/assault-rifles/hemlock-trial-by-fire.png'),
        honor: require('../../assets/armory/assault-rifles/hemlock-code-of-honor.png'),
        grid: require('../../assets/armory/assault-rifles/hemlock-off-the-grid.png'),
        enemy: require('../../assets/armory/assault-rifles/hemlock-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/assault-rifles/hemlock-out-for-blood.png'),
        surprise: require('../../assets/armory/assault-rifles/hemlock-surprise-party.png'),
        carnivale: require('../../assets/armory/assault-rifles/hemlock-carnivale.png'),
        solar: require('../../assets/armory/assault-rifles/hemlock-solar-flare.png'),
        wildlands: require('../../assets/armory/assault-rifles/hemlock-wildlands.png'),
        headgames: require('../../assets/armory/assault-rifles/hemlock-headgames.png'),
        paper: require('../../assets/armory/assault-rifles/hemlock-paper-trail.png'),
        icebreaker: require('../../assets/armory/assault-rifles/hemlock-icebreaker.png'),
        trident: require('../../assets/armory/assault-rifles/hemlock-trident.png'),
        tagged: require('../../assets/armory/assault-rifles/hemlock-tagged.png'),
        rave: require('../../assets/armory/assault-rifles/hemlock-warm-rave.png'),
        urban: require('../../assets/armory/assault-rifles/hemlock-urban-edge.png'),
        recluse: require('../../assets/armory/assault-rifles/hemlock-recluse.png'),
        wave: require('../../assets/armory/assault-rifles/hemlock-cold-wave.png'),
        afterimage: require('../../assets/armory/assault-rifles/hemlock-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/assault-rifles/hemlock-midnight.png'),
        cardinal: require('../../assets/armory/assault-rifles/hemlock-cardinal.png'),
        artic: require('../../assets/armory/assault-rifles/hemlock-artic.png'),
        sunfire: require('../../assets/armory/assault-rifles/hemlock-sunfire.png'),
        clearwater: require('../../assets/armory/assault-rifles/hemlock-clearwater.png'),
        flamingo: require('../../assets/armory/assault-rifles/hemlock-flamingo.png'),
        sandstorm: require('../../assets/armory/assault-rifles/hemlock-sandstorm.png'),
        rainforest: require('../../assets/armory/assault-rifles/hemlock-rainforest.png'),
        evergreen: require('../../assets/armory/assault-rifles/hemlock-evergreen.png'),
        orchid: require('../../assets/armory/assault-rifles/hemlock-orchid.png'),
        bengal: require('../../assets/armory/assault-rifles/hemlock-bengal.png'),
        yellowjacket: require('../../assets/armory/assault-rifles/hemlock-yellowjacket.png'),
        lagoon: require('../../assets/armory/assault-rifles/hemlock-lagoon.png'),
        clover: require('../../assets/armory/assault-rifles/hemlock-clover.png'),
        oceanic: require('../../assets/armory/assault-rifles/hemlock-oceanic.png'),
    },
    R301:{
        // Default Skin
        factory: require('../../assets/armory/assault-rifles/r-301-factory-issue.png'),
        // Legendary Skins
        theLastSpartan: require('../../assets/armory/assault-rifles/r-301-the-last-spartan.png'),
        theDaybreaker: require('../../assets/armory/assault-rifles/r-301-the-daybreaker.png'),
        unsheathedRebellion: require('../../assets/armory/assault-rifles/r-301-unsheathed-rebellion.png'),
        dynasticCycle: require('../../assets/armory/assault-rifles/r-301-dynastic-cycle.png'),
        // Epic Skins
        storm: require('../../assets/armory/assault-rifles/r-301-eye-of-the-storm.png'),
        trial: require('../../assets/armory/assault-rifles/r-301-trial-by-fire.png'),
        honor: require('../../assets/armory/assault-rifles/r-301-code-of-honor.png'),
        grid: require('../../assets/armory/assault-rifles/r-301-off-the-grid.png'),
        enemy: require('../../assets/armory/assault-rifles/r-301-break-the-enemy.png'),
        // Rare Skins
        solstice: require('../../assets/armory/assault-rifles/r-301-solstice.png'),
        warlord: require('../../assets/armory/assault-rifles/r-301-warlord.png'),
        shockwave: require('../../assets/armory/assault-rifles/r-301-shockwave.png'),
        fair: require('../../assets/armory/assault-rifles/r-301-fun-fair.png'),
        rock: require('../../assets/armory/assault-rifles/r-301-rock-bed.png'),
        kaleidoscope: require('../../assets/armory/assault-rifles/r-301-kaleidoscope.png'),
        clockwork: require('../../assets/armory/assault-rifles/r-301-clockwork.png'),
        slither: require('../../assets/armory/assault-rifles/r-301-slither.png'),
        ladybug: require('../../assets/armory/assault-rifles/r-301-ladybug.png'),
        envy: require('../../assets/armory/assault-rifles/r-301-envy.png'),
        nile: require('../../assets/armory/assault-rifles/r-301-nile.png'),
        coral: require('../../assets/armory/assault-rifles/r-301-coral-reef.png'),
        morning: require('../../assets/armory/assault-rifles/r-301-morning-dew.png'),
        cosmos: require('../../assets/armory/assault-rifles/r-301-cosmos.png'),
        zeal: require('../../assets/armory/assault-rifles/r-301-zeal.png'),
        // Common Skins
        midnight: require('../../assets/armory/assault-rifles/r-301-midnight.png'),
        cardinal: require('../../assets/armory/assault-rifles/r-301-cardinal.png'),
        artic: require('../../assets/armory/assault-rifles/r-301-artic.png'),
        sunfire: require('../../assets/armory/assault-rifles/r-301-sunfire.png'),
        clearwater: require('../../assets/armory/assault-rifles/r-301-clearwater.png'),
        flamingo: require('../../assets/armory/assault-rifles/r-301-flamingo.png'),
        sandstorm: require('../../assets/armory/assault-rifles/r-301-sandstorm.png'),
        rainforest: require('../../assets/armory/assault-rifles/r-301-rainforest.png'),
        evergreen: require('../../assets/armory/assault-rifles/r-301-evergreen.png'),
        orchid: require('../../assets/armory/assault-rifles/r-301-orchid.png'),
        bengal: require('../../assets/armory/assault-rifles/r-301-bengal.png'),
        yellowjacket: require('../../assets/armory/assault-rifles/r-301-yellowjacket.png'),
        lagoon: require('../../assets/armory/assault-rifles/r-301-lagoon.png'),
        clover: require('../../assets/armory/assault-rifles/r-301-clover.png'),
        oceanic: require('../../assets/armory/assault-rifles/r-301-oceanic.png'),
    },
    HAVOC:{
        // Default Skin
        factory: require('../../assets/armory/assault-rifles/havoc-factory-issue.png'),
        // Legendary Skins
        quantumChaos: require('../../assets/armory/assault-rifles/havoc-quantum-chaos.png'),
        sonicEmpire: require('../../assets/armory/assault-rifles/havoc-sonic-empire.png'),
        // Epic Skins
        storm: require('../../assets/armory/assault-rifles/havoc-eye-of-the-storm.png'),
        trial: require('../../assets/armory/assault-rifles/havoc-trial-by-fire.png'),
        honor: require('../../assets/armory/assault-rifles/havoc-code-of-honor.png'),
        grid: require('../../assets/armory/assault-rifles/havoc-off-the-grid.png'),
        enemy: require('../../assets/armory/assault-rifles/havoc-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/assault-rifles/havoc-out-for-blood.png'),
        surprise: require('../../assets/armory/assault-rifles/havoc-surprise-party.png'),
        carnivale: require('../../assets/armory/assault-rifles/havoc-carnivale.png'),
        solar: require('../../assets/armory/assault-rifles/havoc-solar-flare.png'),
        wildlands: require('../../assets/armory/assault-rifles/havoc-wildlands.png'),
        headgames: require('../../assets/armory/assault-rifles/havoc-headgames.png'),
        paper: require('../../assets/armory/assault-rifles/havoc-paper-trail.png'),
        icebreaker: require('../../assets/armory/assault-rifles/havoc-icebreaker.png'),
        trident: require('../../assets/armory/assault-rifles/havoc-trident.png'),
        tagged: require('../../assets/armory/assault-rifles/havoc-tagged.png'),
        rave: require('../../assets/armory/assault-rifles/havoc-warm-rave.png'),
        urban: require('../../assets/armory/assault-rifles/havoc-urban-edge.png'),
        recluse: require('../../assets/armory/assault-rifles/havoc-recluse.png'),
        wave: require('../../assets/armory/assault-rifles/havoc-cold-wave.png'),
        afterimage: require('../../assets/armory/assault-rifles/havoc-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/assault-rifles/havoc-midnight.png'),
        cardinal: require('../../assets/armory/assault-rifles/havoc-cardinal.png'),
        artic: require('../../assets/armory/assault-rifles/havoc-artic.png'),
        sunfire: require('../../assets/armory/assault-rifles/havoc-sunfire.png'),
        clearwater: require('../../assets/armory/assault-rifles/havoc-clearwater.png'),
        flamingo: require('../../assets/armory/assault-rifles/havoc-flamingo.png'),
        sandstorm: require('../../assets/armory/assault-rifles/havoc-sandstorm.png'),
        rainforest: require('../../assets/armory/assault-rifles/havoc-rainforest.png'),
        evergreen: require('../../assets/armory/assault-rifles/havoc-evergreen.png'),
        orchid: require('../../assets/armory/assault-rifles/havoc-orchid.png'),
        bengal: require('../../assets/armory/assault-rifles/havoc-bengal.png'),
        yellowjacket: require('../../assets/armory/assault-rifles/havoc-yellowjacket.png'),
        lagoon: require('../../assets/armory/assault-rifles/havoc-lagoon.png'),
        clover: require('../../assets/armory/assault-rifles/havoc-clover.png'),
        oceanic: require('../../assets/armory/assault-rifles/havoc-oceanic.png'),
    },
    // Sub Machine Gun Skins
    ALTERNATOR:{
        // Default Skin
        factory: require('../../assets/armory/sub-machine-guns/alternator-factory-issue.png'),
        // Legendary Skins
        theAlternativeRemedy: require('../../assets/armory/sub-machine-guns/alternator-the-alternative-remedy.png'),
        searchAndRescue: require('../../assets/armory/sub-machine-guns/alternator-search-and-rescue.png'),
        ledRez: require('../../assets/armory/sub-machine-guns/alternator-led-rez.png'),
        theGalvanizer: require('../../assets/armory/sub-machine-guns/alternator-the-galvanizer.png'),
        thePlaceboEffect: require('../../assets/armory/sub-machine-guns/alternator-the-placebo-effect.png'),
        // Epic Skins
        storm: require('../../assets/armory/sub-machine-guns/alternator-eye-of-the-storm.png'),
        trial: require('../../assets/armory/sub-machine-guns/alternator-trial-by-fire.png'),
        honor: require('../../assets/armory/sub-machine-guns/alternator-code-of-honor.png'),
        grid: require('../../assets/armory/sub-machine-guns/alternator-off-the-grid.png'),
        enemy: require('../../assets/armory/sub-machine-guns/alternator-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/sub-machine-guns/alternator-out-for-blood.png'),
        surprise: require('../../assets/armory/sub-machine-guns/alternator-surprise-party.png'),
        carnivale: require('../../assets/armory/sub-machine-guns/alternator-carnivale.png'),
        solar: require('../../assets/armory/sub-machine-guns/alternator-solar-flare.png'),
        wildlands: require('../../assets/armory/sub-machine-guns/alternator-wildlands.png'),
        headgames: require('../../assets/armory/sub-machine-guns/alternator-headgames.png'),
        paper: require('../../assets/armory/sub-machine-guns/alternator-paper-trail.png'),
        icebreaker: require('../../assets/armory/sub-machine-guns/alternator-icebreaker.png'),
        trident: require('../../assets/armory/sub-machine-guns/alternator-trident.png'),
        tagged: require('../../assets/armory/sub-machine-guns/alternator-tagged.png'),
        rave: require('../../assets/armory/sub-machine-guns/alternator-warm-rave.png'),
        urban: require('../../assets/armory/sub-machine-guns/alternator-urban-edge.png'),
        recluse: require('../../assets/armory/sub-machine-guns/alternator-recluse.png'),
        wave: require('../../assets/armory/sub-machine-guns/alternator-cold-wave.png'),
        afterimage: require('../../assets/armory/sub-machine-guns/alternator-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/sub-machine-guns/alternator-midnight.png'),
        cardinal: require('../../assets/armory/sub-machine-guns/alternator-cardinal.png'),
        artic: require('../../assets/armory/sub-machine-guns/alternator-artic.png'),
        sunfire: require('../../assets/armory/sub-machine-guns/alternator-sunfire.png'),
        clearwater: require('../../assets/armory/sub-machine-guns/alternator-clearwater.png'),
        flamingo: require('../../assets/armory/sub-machine-guns/alternator-flamingo.png'),
        sandstorm: require('../../assets/armory/sub-machine-guns/alternator-sandstorm.png'),
        rainforest: require('../../assets/armory/sub-machine-guns/alternator-rainforest.png'),
        evergreen: require('../../assets/armory/sub-machine-guns/alternator-evergreen.png'),
        orchid: require('../../assets/armory/sub-machine-guns/alternator-orchid.png'),
        bengal: require('../../assets/armory/sub-machine-guns/alternator-bengal.png'),
        yellowjacket: require('../../assets/armory/sub-machine-guns/alternator-yellowjacket.png'),
        lagoon: require('../../assets/armory/sub-machine-guns/alternator-lagoon.png'),
        clover: require('../../assets/armory/sub-machine-guns/alternator-clover.png'),
        oceanic: require('../../assets/armory/sub-machine-guns/alternator-oceanic.png'),
    },
    R99:{
        // Default Skin
        factory: require('../../assets/armory/sub-machine-guns/r-99-factory-issue.png'),
        // Legendary Skins
        theProblemSolver: require('../../assets/armory/sub-machine-guns/r-99-the-problem-solver.png'),
        theAlchemist: require('../../assets/armory/sub-machine-guns/r-99-the-alchemist.png'),
        outlandsAvalanche: require('../../assets/armory/sub-machine-guns/r-99-outlands-avalanche.png'),
        theKillSwitch: require('../../assets/armory/sub-machine-guns/r-99-the-kill-switch.png'),
        // Epic Skins
        storm: require('../../assets/armory/sub-machine-guns/r-99-eye-of-the-storm.png'),
        trial: require('../../assets/armory/sub-machine-guns/r-99-trial-by-fire.png'),
        honor: require('../../assets/armory/sub-machine-guns/r-99-code-of-honor.png'),
        grid: require('../../assets/armory/sub-machine-guns/r-99-off-the-grid.png'),
        enemy: require('../../assets/armory/sub-machine-guns/r-99-break-the-enemy.png'),
        // Rare Skins
        solstice: require('../../assets/armory/sub-machine-guns/r-99-solstice.png'),
        warlord: require('../../assets/armory/sub-machine-guns/r-99-warlord.png'),
        shockwave: require('../../assets/armory/sub-machine-guns/r-99-shockwave.png'),
        fair: require('../../assets/armory/sub-machine-guns/r-99-fun-fair.png'),
        rock: require('../../assets/armory/sub-machine-guns/r-99-rock-bed.png'),
        kaleidoscope: require('../../assets/armory/sub-machine-guns/r-99-kaleidoscope.png'),
        clockwork: require('../../assets/armory/sub-machine-guns/r-99-clockwork.png'),
        slither: require('../../assets/armory/sub-machine-guns/r-99-slither.png'),
        ladybug: require('../../assets/armory/sub-machine-guns/r-99-ladybug.png'),
        envy: require('../../assets/armory/sub-machine-guns/r-99-envy.png'),
        nile: require('../../assets/armory/sub-machine-guns/r-99-nile.png'),
        coral: require('../../assets/armory/sub-machine-guns/r-99-coral-reef.png'),
        morning: require('../../assets/armory/sub-machine-guns/r-99-morning-dew.png'),
        cosmos: require('../../assets/armory/sub-machine-guns/r-99-cosmos.png'),
        zeal: require('../../assets/armory/sub-machine-guns/r-99-zeal.png'),
        // Common Skins
        midnight: require('../../assets/armory/sub-machine-guns/r-99-midnight.png'),
        cardinal: require('../../assets/armory/sub-machine-guns/r-99-cardinal.png'),
        artic: require('../../assets/armory/sub-machine-guns/r-99-artic.png'),
        sunfire: require('../../assets/armory/sub-machine-guns/r-99-sunfire.png'),
        clearwater: require('../../assets/armory/sub-machine-guns/r-99-clearwater.png'),
        flamingo: require('../../assets/armory/sub-machine-guns/r-99-flamingo.png'),
        sandstorm: require('../../assets/armory/sub-machine-guns/r-99-sandstorm.png'),
        rainforest: require('../../assets/armory/sub-machine-guns/r-99-rainforest.png'),
        evergreen: require('../../assets/armory/sub-machine-guns/r-99-evergreen.png'),
        orchid: require('../../assets/armory/sub-machine-guns/r-99-orchid.png'),
        bengal: require('../../assets/armory/sub-machine-guns/r-99-bengal.png'),
        yellowjacket: require('../../assets/armory/sub-machine-guns/r-99-yellowjacket.png'),
        lagoon: require('../../assets/armory/sub-machine-guns/r-99-lagoon.png'),
        clover: require('../../assets/armory/sub-machine-guns/r-99-clover.png'),
        oceanic: require('../../assets/armory/sub-machine-guns/r-99-oceanic.png'),
    },
    PROWLER: {
        // Default Skin
        factory: require('../../assets/armory/sub-machine-guns/prowler-factory-issue.png'),
        // Legendary Skins
        theBulletContagion: require('../../assets/armory/sub-machine-guns/prowler-the-bullet-contagion.png'),
        spacewalker: require('../../assets/armory/sub-machine-guns/prowler-spacewalker.png'),
        theDarkRealm: require('../../assets/armory/sub-machine-guns/prowler-the-dark-realm.png'),
        theLightworker: require('../../assets/armory/sub-machine-guns/prowler-the-lightworker.png'),
        // Epic Skins
        storm: require('../../assets/armory/sub-machine-guns/prowler-eye-of-the-storm.png'),
        trial: require('../../assets/armory/sub-machine-guns/prowler-trial-by-fire.png'),
        honor: require('../../assets/armory/sub-machine-guns/prowler-code-of-honor.png'),
        grid: require('../../assets/armory/sub-machine-guns/prowler-off-the-grid.png'),
        enemy: require('../../assets/armory/sub-machine-guns/prowler-break-the-enemy.png'),
        // Rare Skins
        generation: require('../../assets/armory/sub-machine-guns/prowler-generation-x.png'),
        outback: require('../../assets/armory/sub-machine-guns/prowler-outback.png'),
        sweet: require('../../assets/armory/sub-machine-guns/prowler-sweet-16.png'),
        fusion: require('../../assets/armory/sub-machine-guns/prowler-cold-fusion.png'),
        shattered: require('../../assets/armory/sub-machine-guns/prowler-shattered.png'),
        stellar: require('../../assets/armory/sub-machine-guns/prowler-stellar.png'),
        jungle: require('../../assets/armory/sub-machine-guns/prowler-jungle-frenzy.png'),
        cloudburst: require('../../assets/armory/sub-machine-guns/prowler-cloudburst.png'),
        yellow: require('../../assets/armory/sub-machine-guns/prowler-yellow-snake.png'),
        skyrise: require('../../assets/armory/sub-machine-guns/prowler-skyrise.png'),
        jester: require('../../assets/armory/sub-machine-guns/prowler-jester.png'),
        derez: require('../../assets/armory/sub-machine-guns/prowler-derez.png'),
        chaos: require('../../assets/armory/sub-machine-guns/prowler-chaos-theory.png'),
        triumphant: require('../../assets/armory/sub-machine-guns/prowler-triumphant-arch.png'),
        newmoon: require('../../assets/armory/sub-machine-guns/prowler-new-moon.png'),
        // Common Skins
        midnight: require('../../assets/armory/sub-machine-guns/prowler-midnight.png'),
        cardinal: require('../../assets/armory/sub-machine-guns/prowler-cardinal.png'),
        artic: require('../../assets/armory/sub-machine-guns/prowler-artic.png'),
        sunfire: require('../../assets/armory/sub-machine-guns/prowler-sunfire.png'),
        clearwater: require('../../assets/armory/sub-machine-guns/prowler-clearwater.png'),
        flamingo: require('../../assets/armory/sub-machine-guns/prowler-flamingo.png'),
        sandstorm: require('../../assets/armory/sub-machine-guns/prowler-sandstorm.png'),
        rainforest: require('../../assets/armory/sub-machine-guns/prowler-rainforest.png'),
        evergreen: require('../../assets/armory/sub-machine-guns/prowler-evergreen.png'),
        orchid: require('../../assets/armory/sub-machine-guns/prowler-orchid.png'),
        bengal: require('../../assets/armory/sub-machine-guns/prowler-bengal.png'),
        yellowjacket: require('../../assets/armory/sub-machine-guns/prowler-yellowjacket.png'),
        lagoon: require('../../assets/armory/sub-machine-guns/prowler-lagoon.png'),
        clover: require('../../assets/armory/sub-machine-guns/prowler-clover.png'),
        oceanic: require('../../assets/armory/sub-machine-guns/prowler-oceanic.png'),
    },
    // Light Machine Gun Skins
    DEVOTION:{
        // Default Skin
        factory: require('../../assets/armory/light-machine-guns/devotion-factory-issue.png'),
        // Legendary Skins
        nitroKustom: require('../../assets/armory/light-machine-guns/devotion-nitro-kustom.png'),
        theLuckyRabbit: require('../../assets/armory/light-machine-guns/devotion-the-lucky-rabbit.png'),
        theLeadFarmer: require('../../assets/armory/light-machine-guns/devotion-the-lead-farmer.png'),
        theFastTrack: require('../../assets/armory/light-machine-guns/devotion-the-fast-track.png'),
        tidalWave: require('../../assets/armory/light-machine-guns/devotion-tidal-wave.png'),
        // Epic Skins
        storm: require('../../assets/armory/light-machine-guns/devotion-eye-of-the-storm.png'),
        trial: require('../../assets/armory/light-machine-guns/devotion-trial-by-fire.png'),
        honor: require('../../assets/armory/light-machine-guns/devotion-code-of-honor.png'),
        grid: require('../../assets/armory/light-machine-guns/devotion-off-the-grid.png'),
        enemy: require('../../assets/armory/light-machine-guns/devotion-break-the-enemy.png'),
        // Rare Skins
        solstice: require('../../assets/armory/light-machine-guns/devotion-solstice.png'),
        warlord: require('../../assets/armory/light-machine-guns/devotion-warlord.png'),
        shockwave: require('../../assets/armory/light-machine-guns/devotion-shockwave.png'),
        fair: require('../../assets/armory/light-machine-guns/devotion-fun-fair.png'),
        rock: require('../../assets/armory/light-machine-guns/devotion-rock-bed.png'),
        kaleidoscope: require('../../assets/armory/light-machine-guns/devotion-kaleidoscope.png'),
        clockwork: require('../../assets/armory/light-machine-guns/devotion-clockwork.png'),
        slither: require('../../assets/armory/light-machine-guns/devotion-slither.png'),
        ladybug: require('../../assets/armory/light-machine-guns/devotion-ladybug.png'),
        envy: require('../../assets/armory/light-machine-guns/devotion-envy.png'),
        nile: require('../../assets/armory/light-machine-guns/devotion-nile.png'),
        coral: require('../../assets/armory/light-machine-guns/devotion-coral-reef.png'),
        morning: require('../../assets/armory/light-machine-guns/devotion-morning-dew.png'),
        cosmos: require('../../assets/armory/light-machine-guns/devotion-cosmos.png'),
        zeal: require('../../assets/armory/light-machine-guns/devotion-zeal.png'),
        // Common Skins
        midnight: require('../../assets/armory/light-machine-guns/devotion-midnight.png'),
        cardinal: require('../../assets/armory/light-machine-guns/devotion-cardinal.png'),
        artic: require('../../assets/armory/light-machine-guns/devotion-artic.png'),
        sunfire: require('../../assets/armory/light-machine-guns/devotion-sunfire.png'),
        clearwater: require('../../assets/armory/light-machine-guns/devotion-clearwater.png'),
        flamingo: require('../../assets/armory/light-machine-guns/devotion-flamingo.png'),
        sandstorm: require('../../assets/armory/light-machine-guns/devotion-sandstorm.png'),
        rainforest: require('../../assets/armory/light-machine-guns/devotion-rainforest.png'),
        evergreen: require('../../assets/armory/light-machine-guns/devotion-evergreen.png'),
        orchid: require('../../assets/armory/light-machine-guns/devotion-orchid.png'),
        bengal: require('../../assets/armory/light-machine-guns/devotion-bengal.png'),
        yellowjacket: require('../../assets/armory/light-machine-guns/devotion-yellowjacket.png'),
        lagoon: require('../../assets/armory/light-machine-guns/devotion-lagoon.png'),
        clover: require('../../assets/armory/light-machine-guns/devotion-clover.png'),
        oceanic: require('../../assets/armory/light-machine-guns/devotion-oceanic.png'),
    },
    SPITFIRE:{
        // Default Skin
        factory: require('../../assets/armory/light-machine-guns/spitfire-factory-issue.png'),
        // Legendary Skins
        flyingWarhawk: require('../../assets/armory/light-machine-guns/spitfire-flying-warhawk.png'),
        originalMarauder: require('../../assets/armory/light-machine-guns/spitfire-original-marauder.png'),
        theContinuum: require('../../assets/armory/light-machine-guns/spitfire-the-continuum.png'),
        theHeavyConstruct: require('../../assets/armory/light-machine-guns/spitfire-the-heavy-construct.png'),
        // Epic Skins
        storm: require('../../assets/armory/light-machine-guns/spitfire-eye-of-the-storm.png'),
        trial: require('../../assets/armory/light-machine-guns/spitfire-trial-by-fire.png'),
        honor: require('../../assets/armory/light-machine-guns/spitfire-code-of-honor.png'),
        grid: require('../../assets/armory/light-machine-guns/spitfire-off-the-grid.png'),
        enemy: require('../../assets/armory/light-machine-guns/spitfire-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/light-machine-guns/spitfire-out-for-blood.png'),
        surprise: require('../../assets/armory/light-machine-guns/spitfire-surprise-party.png'),
        carnivale: require('../../assets/armory/light-machine-guns/spitfire-carnivale.png'),
        solar: require('../../assets/armory/light-machine-guns/spitfire-solar-flare.png'),
        wildlands: require('../../assets/armory/light-machine-guns/spitfire-wildlands.png'),
        headgames: require('../../assets/armory/light-machine-guns/spitfire-headgames.png'),
        paper: require('../../assets/armory/light-machine-guns/spitfire-paper-trail.png'),
        icebreaker: require('../../assets/armory/light-machine-guns/spitfire-icebreaker.png'),
        trident: require('../../assets/armory/light-machine-guns/spitfire-trident.png'),
        tagged: require('../../assets/armory/light-machine-guns/spitfire-tagged.png'),
        rave: require('../../assets/armory/light-machine-guns/spitfire-warm-rave.png'),
        urban: require('../../assets/armory/light-machine-guns/spitfire-urban-edge.png'),
        recluse: require('../../assets/armory/light-machine-guns/spitfire-recluse.png'),
        wave: require('../../assets/armory/light-machine-guns/spitfire-cold-wave.png'),
        afterimage: require('../../assets/armory/light-machine-guns/spitfire-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/light-machine-guns/spitfire-midnight.png'),
        cardinal: require('../../assets/armory/light-machine-guns/spitfire-cardinal.png'),
        artic: require('../../assets/armory/light-machine-guns/spitfire-artic.png'),
        sunfire: require('../../assets/armory/light-machine-guns/spitfire-sunfire.png'),
        clearwater: require('../../assets/armory/light-machine-guns/spitfire-clearwater.png'),
        flamingo: require('../../assets/armory/light-machine-guns/spitfire-flamingo.png'),
        sandstorm: require('../../assets/armory/light-machine-guns/spitfire-sandstorm.png'),
        rainforest: require('../../assets/armory/light-machine-guns/spitfire-rainforest.png'),
        evergreen: require('../../assets/armory/light-machine-guns/spitfire-evergreen.png'),
        orchid: require('../../assets/armory/light-machine-guns/spitfire-orchid.png'),
        bengal: require('../../assets/armory/light-machine-guns/spitfire-bengal.png'),
        yellowjacket: require('../../assets/armory/light-machine-guns/spitfire-yellowjacket.png'),
        lagoon: require('../../assets/armory/light-machine-guns/spitfire-lagoon.png'),
        clover: require('../../assets/armory/light-machine-guns/spitfire-clover.png'),
        oceanic: require('../../assets/armory/light-machine-guns/spitfire-oceanic.png'),
    },
    // Sniper Rifle Skins
    SCOUT:{
        // Default Skin
        factory: require('../../assets/armory/sniper-rifles/g7-scout-factory-issue.png'),
        // Legendary Skins
        theGoldenDragon: require('../../assets/armory/sniper-rifles/g7-scout-the-gold-dragon.png'),
        theCrimsonFiredrake: require('../../assets/armory/sniper-rifles/g7-scout-the-crimson-firedrake.png'),
        thePreyStalker: require('../../assets/armory/sniper-rifles/g7-scout-the-prey-stalker.png'),
        coldJustice: require('../../assets/armory/sniper-rifles/g7-scout-cold-justice.png'),
        // Epic Skins
        storm: require('../../assets/armory/sniper-rifles/g7-scout-eye-of-the-storm.png'),
        trial: require('../../assets/armory/sniper-rifles/g7-scout-trial-by-fire.png'),
        honor: require('../../assets/armory/sniper-rifles/g7-scout-code-of-honor.png'),
        grid: require('../../assets/armory/sniper-rifles/g7-scout-off-the-grid.png'),
        enemy: require('../../assets/armory/sniper-rifles/g7-scout-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/sniper-rifles/g7-scout-out-for-blood.png'),
        surprise: require('../../assets/armory/sniper-rifles/g7-scout-surprise-party.png'),
        carnivale: require('../../assets/armory/sniper-rifles/g7-scout-carnivale.png'),
        solar: require('../../assets/armory/sniper-rifles/g7-scout-solar-flare.png'),
        wildlands: require('../../assets/armory/sniper-rifles/g7-scout-wildlands.png'),
        headgames: require('../../assets/armory/sniper-rifles/g7-scout-headgames.png'),
        paper: require('../../assets/armory/sniper-rifles/g7-scout-paper-trail.png'),
        icebreaker: require('../../assets/armory/sniper-rifles/g7-scout-icebreaker.png'),
        trident: require('../../assets/armory/sniper-rifles/g7-scout-trident.png'),
        tagged: require('../../assets/armory/sniper-rifles/g7-scout-tagged.png'),
        rave: require('../../assets/armory/sniper-rifles/g7-scout-warm-rave.png'),
        urban: require('../../assets/armory/sniper-rifles/g7-scout-urban-edge.png'),
        recluse: require('../../assets/armory/sniper-rifles/g7-scout-recluse.png'),
        wave: require('../../assets/armory/sniper-rifles/g7-scout-cold-wave.png'),
        afterimage: require('../../assets/armory/sniper-rifles/g7-scout-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/sniper-rifles/g7-scout-midnight.png'),
        cardinal: require('../../assets/armory/sniper-rifles/g7-scout-cardinal.png'),
        artic: require('../../assets/armory/sniper-rifles/g7-scout-artic.png'),
        sunfire: require('../../assets/armory/sniper-rifles/g7-scout-sunfire.png'),
        clearwater: require('../../assets/armory/sniper-rifles/g7-scout-clearwater.png'),
        flamingo: require('../../assets/armory/sniper-rifles/g7-scout-flamingo.png'),
        sandstorm: require('../../assets/armory/sniper-rifles/g7-scout-sandstorm.png'),
        rainforest: require('../../assets/armory/sniper-rifles/g7-scout-rainforest.png'),
        evergreen: require('../../assets/armory/sniper-rifles/g7-scout-evergreen.png'),
        orchid: require('../../assets/armory/sniper-rifles/g7-scout-orchid.png'),
        bengal: require('../../assets/armory/sniper-rifles/g7-scout-bengal.png'),
        yellowjacket: require('../../assets/armory/sniper-rifles/g7-scout-yellowjacket.png'),
        lagoon: require('../../assets/armory/sniper-rifles/g7-scout-lagoon.png'),
        clover: require('../../assets/armory/sniper-rifles/g7-scout-clover.png'),
        oceanic: require('../../assets/armory/sniper-rifles/g7-scout-oceanic.png'),
    },
    LONGBOW:{
        // Default Skin
        factory: require('../../assets/armory/sniper-rifles/longbow-factory-issue.png'),
        // Legendary SkinS
        bigGameHunter: require('../../assets/armory/sniper-rifles/longbow-big-game-hunter.png'),
        nocturnalPredator: require('../../assets/armory/sniper-rifles/longbow-nocturnal-predator.png'),
        sleeperCell: require('../../assets/armory/sniper-rifles/longbow-sleeper-cell.png'),
        defcon1: require('../../assets/armory/sniper-rifles/longbow-defcon-1.png'),
        // Epic Skins
        storm: require('../../assets/armory/sniper-rifles/longbow-eye-of-the-storm.png'),
        trial: require('../../assets/armory/sniper-rifles/longbow-trial-by-fire.png'),
        honor: require('../../assets/armory/sniper-rifles/longbow-code-of-honor.png'),
        grid: require('../../assets/armory/sniper-rifles/longbow-off-the-grid.png'),
        enemy: require('../../assets/armory/sniper-rifles/longbow-break-the-enemy.png'),
        // Rare Skins
        generation: require('../../assets/armory/sniper-rifles/longbow-generation-x.png'),
        outback: require('../../assets/armory/sniper-rifles/longbow-outback.png'),
        sweet: require('../../assets/armory/sniper-rifles/longbow-sweet-16.png'),
        fusion: require('../../assets/armory/sniper-rifles/longbow-cold-fusion.png'),
        shattered: require('../../assets/armory/sniper-rifles/longbow-shattered.png'),
        stellar: require('../../assets/armory/sniper-rifles/longbow-stellar.png'),
        jungle: require('../../assets/armory/sniper-rifles/longbow-jungle-frenzy.png'),
        cloudburst: require('../../assets/armory/sniper-rifles/longbow-cloudburst.png'),
        yellow: require('../../assets/armory/sniper-rifles/longbow-yellow-snake.png'),
        skyrise: require('../../assets/armory/sniper-rifles/longbow-skyrise.png'),
        jester: require('../../assets/armory/sniper-rifles/longbow-jester.png'),
        derez: require('../../assets/armory/sniper-rifles/longbow-derez.png'),
        chaos: require('../../assets/armory/sniper-rifles/longbow-chaos-theory.png'),
        triumphant: require('../../assets/armory/sniper-rifles/longbow-triumphant-arch.png'),
        newmoon: require('../../assets/armory/sniper-rifles/longbow-new-moon.png'),
        // Common Skins
        midnight: require('../../assets/armory/sniper-rifles/longbow-midnight.png'),
        cardinal: require('../../assets/armory/sniper-rifles/longbow-cardinal.png'),
        artic: require('../../assets/armory/sniper-rifles/longbow-artic.png'),
        sunfire: require('../../assets/armory/sniper-rifles/longbow-sunfire.png'),
        clearwater: require('../../assets/armory/sniper-rifles/longbow-clearwater.png'),
        flamingo: require('../../assets/armory/sniper-rifles/longbow-flamingo.png'),
        sandstorm: require('../../assets/armory/sniper-rifles/longbow-sandstorm.png'),
        rainforest: require('../../assets/armory/sniper-rifles/longbow-rainforest.png'),
        evergreen: require('../../assets/armory/sniper-rifles/longbow-evergreen.png'),
        orchid: require('../../assets/armory/sniper-rifles/longbow-orchid.png'),
        bengal: require('../../assets/armory/sniper-rifles/longbow-bengal.png'),
        yellowjacket: require('../../assets/armory/sniper-rifles/longbow-yellowjacket.png'),
        lagoon: require('../../assets/armory/sniper-rifles/longbow-lagoon.png'),
        clover: require('../../assets/armory/sniper-rifles/longbow-clover.png'),
        oceanic: require('../../assets/armory/sniper-rifles/longbow-oceanic.png'),
    },
    TRIPLETAKE:{
        // Default Skin
        factory: require('../../assets/armory/sniper-rifles/triple-take-factory-issue.png'),
        // Legendary Skins
        firstStrike: require('../../assets/armory/sniper-rifles/triple-take-first-strike.png'),
        absoluteZero: require('../../assets/armory/sniper-rifles/triple-take-absolute-zero.png'),
        theInvader: require('../../assets/armory/sniper-rifles/triple-take-the-invader.png'),
        tripleCrown: require('../../assets/armory/sniper-rifles/triple-take-triple-crown.png'),
        // Epic Skins
        storm: require('../../assets/armory/sniper-rifles/triple-take-eye-of-the-storm.png'),
        trial: require('../../assets/armory/sniper-rifles/triple-take-trial-by-fire.png'),
        honor: require('../../assets/armory/sniper-rifles/triple-take-code-of-honor.png'),
        grid: require('../../assets/armory/sniper-rifles/triple-take-off-the-grid.png'),
        enemy: require('../../assets/armory/sniper-rifles/triple-take-break-the-enemy.png'),
        // Rare Skins
        solstice: require('../../assets/armory/sniper-rifles/triple-take-solstice.png'),
        warlord: require('../../assets/armory/sniper-rifles/triple-take-warlord.png'),
        shockwave: require('../../assets/armory/sniper-rifles/triple-take-shockwave.png'),
        fair: require('../../assets/armory/sniper-rifles/triple-take-fun-fair.png'),
        rock: require('../../assets/armory/sniper-rifles/triple-take-rock-bed.png'),
        kaleidoscope: require('../../assets/armory/sniper-rifles/triple-take-kaleidoscope.png'),
        clockwork: require('../../assets/armory/sniper-rifles/triple-take-clockwork.png'),
        slither: require('../../assets/armory/sniper-rifles/triple-take-slither.png'),
        ladybug: require('../../assets/armory/sniper-rifles/triple-take-ladybug.png'),
        envy: require('../../assets/armory/sniper-rifles/triple-take-envy.png'),
        nile: require('../../assets/armory/sniper-rifles/triple-take-nile.png'),
        coral: require('../../assets/armory/sniper-rifles/triple-take-coral-reef.png'),
        morning: require('../../assets/armory/sniper-rifles/triple-take-morning-dew.png'),
        cosmos: require('../../assets/armory/sniper-rifles/triple-take-cosmos.png'),
        zeal: require('../../assets/armory/sniper-rifles/triple-take-zeal.png'),
        // Common Skins
        midnight: require('../../assets/armory/sniper-rifles/triple-take-midnight.png'),
        cardinal: require('../../assets/armory/sniper-rifles/triple-take-cardinal.png'),
        artic: require('../../assets/armory/sniper-rifles/triple-take-artic.png'),
        sunfire: require('../../assets/armory/sniper-rifles/triple-take-sunfire.png'),
        clearwater: require('../../assets/armory/sniper-rifles/triple-take-clearwater.png'),
        flamingo: require('../../assets/armory/sniper-rifles/triple-take-flamingo.png'),
        sandstorm: require('../../assets/armory/sniper-rifles/triple-take-sandstorm.png'),
        rainforest: require('../../assets/armory/sniper-rifles/triple-take-rainforest.png'),
        evergreen: require('../../assets/armory/sniper-rifles/triple-take-evergreen.png'),
        orchid: require('../../assets/armory/sniper-rifles/triple-take-orchid.png'),
        bengal: require('../../assets/armory/sniper-rifles/triple-take-bengal.png'),
        yellowjacket: require('../../assets/armory/sniper-rifles/triple-take-yellowjacket.png'),
        lagoon: require('../../assets/armory/sniper-rifles/triple-take-lagoon.png'),
        clover: require('../../assets/armory/sniper-rifles/triple-take-clover.png'),
        oceanic: require('../../assets/armory/sniper-rifles/triple-take-oceanic.png'),
    },
    KRABER:{
        // Default Skin
        factory: require('../../assets/armory/sniper-rifles/kraber-factory-issue.png'),
        // Legendary Skins
        theSnowpiercer: require('../../assets/armory/sniper-rifles/kraber-the-snow-piercer.png'),
        theLifeSaver: require('../../assets/armory/sniper-rifles/kraber-the-life-saver.png'),
        // Epic Skins
        storm: require('../../assets/armory/sniper-rifles/kraber-eye-of-the-storm.png'),
        trial: require('../../assets/armory/sniper-rifles/kraber-trial-by-fire.png'),
        honor: require('../../assets/armory/sniper-rifles/kraber-code-of-honor.png'),
        grid: require('../../assets/armory/sniper-rifles/kraber-off-the-grid.png'),
        enemy: require('../../assets/armory/sniper-rifles/kraber-break-the-enemy.png'),
        // Rare Skins
        solstice: require('../../assets/armory/sniper-rifles/kraber-solstice.png'),
        warlord: require('../../assets/armory/sniper-rifles/kraber-warlord.png'),
        shockwave: require('../../assets/armory/sniper-rifles/kraber-shockwave.png'),
        fair: require('../../assets/armory/sniper-rifles/kraber-fun-fair.png'),
        rock: require('../../assets/armory/sniper-rifles/kraber-rock-bed.png'),
        kaleidoscope: require('../../assets/armory/sniper-rifles/kraber-kaleidoscope.png'),
        clockwork: require('../../assets/armory/sniper-rifles/kraber-clockwork.png'),
        slither: require('../../assets/armory/sniper-rifles/kraber-slither.png'),
        ladybug: require('../../assets/armory/sniper-rifles/kraber-ladybug.png'),
        envy: require('../../assets/armory/sniper-rifles/kraber-envy.png'),
        nile: require('../../assets/armory/sniper-rifles/kraber-nile.png'),
        coral: require('../../assets/armory/sniper-rifles/kraber-coral-reef.png'),
        morning: require('../../assets/armory/sniper-rifles/kraber-morning-dew.png'),
        cosmos: require('../../assets/armory/sniper-rifles/kraber-cosmos.png'),
        zeal: require('../../assets/armory/sniper-rifles/kraber-zeal.png'),
        // Common Skins
        midnight: require('../../assets/armory/sniper-rifles/kraber-midnight.png'),
        cardinal: require('../../assets/armory/sniper-rifles/kraber-cardinal.png'),
        artic: require('../../assets/armory/sniper-rifles/kraber-artic.png'),
        sunfire: require('../../assets/armory/sniper-rifles/kraber-sunfire.png'),
        clearwater: require('../../assets/armory/sniper-rifles/kraber-clearwater.png'),
        flamingo: require('../../assets/armory/sniper-rifles/kraber-flamingo.png'),
        sandstorm: require('../../assets/armory/sniper-rifles/kraber-sandstorm.png'),
        rainforest: require('../../assets/armory/sniper-rifles/kraber-rainforest.png'),
        evergreen: require('../../assets/armory/sniper-rifles/kraber-evergreen.png'),
        orchid: require('../../assets/armory/sniper-rifles/kraber-orchid.png'),
        bengal: require('../../assets/armory/sniper-rifles/kraber-bengal.png'),
        yellowjacket: require('../../assets/armory/sniper-rifles/kraber-yellowjacket.png'),
        lagoon: require('../../assets/armory/sniper-rifles/kraber-lagoon.png'),
        clover: require('../../assets/armory/sniper-rifles/kraber-clover.png'),
        oceanic: require('../../assets/armory/sniper-rifles/kraber-oceanic.png'),
    },
    // Shotgun Skins
    EVA8: {
        // Default Skin
        factory: require('../../assets/armory/shotguns/eva-8-auto-factory-issue.png'),
        // Legendary Skins
        theBoneCollector: require('../../assets/armory/shotguns/eva-8-auto-the-bone-collector.png'),
        nobelTruth: require('../../assets/armory/shotguns/eva-8-auto-noble-truth.png'),
        guardiansOfAtlantis: require('../../assets/armory/shotguns/eva-8-auto-guardian-of-atlantis.png'),
        theFirebreather: require('../../assets/armory/shotguns/eva-8-auto-the-firebreather.png'),
        // Epic Skins
        storm: require('../../assets/armory/shotguns/eva-8-auto-eye-of-the-storm.png'),
        trial: require('../../assets/armory/shotguns/eva-8-auto-trial-by-fire.png'),
        honor: require('../../assets/armory/shotguns/eva-8-auto-code-of-honor.png'),
        grid: require('../../assets/armory/shotguns/eva-8-auto-off-the-grid.png'),
        enemy: require('../../assets/armory/shotguns/eva-8-auto-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/shotguns/eva-8-auto-out-for-blood.png'),
        surprise: require('../../assets/armory/shotguns/eva-8-auto-surprise-party.png'),
        carnivale: require('../../assets/armory/shotguns/eva-8-auto-carnivale.png'),
        solar: require('../../assets/armory/shotguns/eva-8-auto-solar-flare.png'),
        wildlands: require('../../assets/armory/shotguns/eva-8-auto-wildlands.png'),
        headgames: require('../../assets/armory/shotguns/eva-8-auto-headgames.png'),
        paper: require('../../assets/armory/shotguns/eva-8-auto-paper-trail.png'),
        icebreaker: require('../../assets/armory/shotguns/eva-8-auto-icebreaker.png'),
        trident: require('../../assets/armory/shotguns/eva-8-auto-trident.png'),
        tagged: require('../../assets/armory/shotguns/eva-8-auto-tagged.png'),
        rave: require('../../assets/armory/shotguns/eva-8-auto-warm-rave.png'),
        urban: require('../../assets/armory/shotguns/eva-8-auto-urban-edge.png'),
        recluse: require('../../assets/armory/shotguns/eva-8-auto-recluse.png'),
        wave: require('../../assets/armory/shotguns/eva-8-auto-cold-wave.png'),
        afterimage: require('../../assets/armory/shotguns/eva-8-auto-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/shotguns/eva-8-auto-midnight.png'),
        cardinal: require('../../assets/armory/shotguns/eva-8-auto-cardinal.png'),
        artic: require('../../assets/armory/shotguns/eva-8-auto-artic.png'),
        sunfire: require('../../assets/armory/shotguns/eva-8-auto-sunfire.png'),
        clearwater: require('../../assets/armory/shotguns/eva-8-auto-clearwater.png'),
        flamingo: require('../../assets/armory/shotguns/eva-8-auto-flamingo.png'),
        sandstorm: require('../../assets/armory/shotguns/eva-8-auto-sandstorm.png'),
        rainforest: require('../../assets/armory/shotguns/eva-8-auto-rainforest.png'),
        evergreen: require('../../assets/armory/shotguns/eva-8-auto-evergreen.png'),
        orchid: require('../../assets/armory/shotguns/eva-8-auto-orchid.png'),
        bengal: require('../../assets/armory/shotguns/eva-8-auto-bengal.png'),
        yellowjacket: require('../../assets/armory/shotguns/eva-8-auto-yellowjacket.png'),
        lagoon: require('../../assets/armory/shotguns/eva-8-auto-lagoon.png'),
        clover: require('../../assets/armory/shotguns/eva-8-auto-clover.png'),
        oceanic: require('../../assets/armory/shotguns/eva-8-auto-oceanic.png'),
    },
    PEACEKEEPER:{
        // Default Skin
        factory: require('../../assets/armory/shotguns/peacekeeper-factory-issue.png'),
        // Legendary Skins
        theLonestar: require('../../assets/armory/shotguns/peacekeeper-the-lonestar.png'),
        theSuperstar: require('../../assets/armory/shotguns/peacekeeper-the-superstar.png'),
        pal9000: require('../../assets/armory/shotguns/peacekeeper-pal-9000.png'),
        theDemolisher: require('../../assets/armory/shotguns/peacekeeper-the-demolisher.png'),
        // Epic Skins
        storm: require('../../assets/armory/shotguns/peacekeeper-eye-of-the-storm.png'),
        trial: require('../../assets/armory/shotguns/peacekeeper-trial-by-fire.png'),
        honor: require('../../assets/armory/shotguns/peacekeeper-code-of-honor.png'),
        grid: require('../../assets/armory/shotguns/peacekeeper-off-the-grid.png'),
        enemy: require('../../assets/armory/shotguns/peacekeeper-break-the-enemy.png'),
        // Rare Skins
        solstice: require('../../assets/armory/shotguns/peacekeeper-solstice.png'),
        warlord: require('../../assets/armory/shotguns/peacekeeper-warlord.png'),
        shockwave: require('../../assets/armory/shotguns/peacekeeper-shockwave.png'),
        fair: require('../../assets/armory/shotguns/peacekeeper-fun-fair.png'),
        rock: require('../../assets/armory/shotguns/peacekeeper-rock-bed.png'),
        kaleidoscope: require('../../assets/armory/shotguns/peacekeeper-kaleidoscope.png'),
        clockwork: require('../../assets/armory/shotguns/peacekeeper-clockwork.png'),
        slither: require('../../assets/armory/shotguns/peacekeeper-slither.png'),
        ladybug: require('../../assets/armory/shotguns/peacekeeper-ladybug.png'),
        envy: require('../../assets/armory/shotguns/peacekeeper-envy.png'),
        nile: require('../../assets/armory/shotguns/peacekeeper-nile.png'),
        coral: require('../../assets/armory/shotguns/peacekeeper-coral-reef.png'),
        morning: require('../../assets/armory/shotguns/peacekeeper-morning-dew.png'),
        cosmos: require('../../assets/armory/shotguns/peacekeeper-cosmos.png'),
        zeal: require('../../assets/armory/shotguns/peacekeeper-zeal.png'),
        // Common Skins
        midnight: require('../../assets/armory/shotguns/peacekeeper-midnight.png'),
        cardinal: require('../../assets/armory/shotguns/peacekeeper-cardinal.png'),
        artic: require('../../assets/armory/shotguns/peacekeeper-artic.png'),
        sunfire: require('../../assets/armory/shotguns/peacekeeper-sunfire.png'),
        clearwater: require('../../assets/armory/shotguns/peacekeeper-clearwater.png'),
        flamingo: require('../../assets/armory/shotguns/peacekeeper-flamingo.png'),
        sandstorm: require('../../assets/armory/shotguns/peacekeeper-sandstorm.png'),
        rainforest: require('../../assets/armory/shotguns/peacekeeper-rainforest.png'),
        evergreen: require('../../assets/armory/shotguns/peacekeeper-evergreen.png'),
        orchid: require('../../assets/armory/shotguns/peacekeeper-orchid.png'),
        bengal: require('../../assets/armory/shotguns/peacekeeper-bengal.png'),
        yellowjacket: require('../../assets/armory/shotguns/peacekeeper-yellowjacket.png'),
        lagoon: require('../../assets/armory/shotguns/peacekeeper-lagoon.png'),
        clover: require('../../assets/armory/shotguns/peacekeeper-clover.png'),
        oceanic: require('../../assets/armory/shotguns/peacekeeper-oceanic.png'),
    },
    MASTIFF:{
        // Default Skin
        factory: require('../../assets/armory/shotguns/mastiff-factory-issue.png'),
        // Legendary Skins
        warpZone: require('../../assets/armory/shotguns/mastiff-warp-zone.png'),
        thePestController: require('../../assets/armory/shotguns/mastiff-the-pest-controller.png'),
        // Epic Skins
        storm: require('../../assets/armory/shotguns/mastiff-eye-of-the-storm.png'),
        trial: require('../../assets/armory/shotguns/mastiff-trial-by-fire.png'),
        honor: require('../../assets/armory/shotguns/mastiff-code-of-honor.png'),
        grid: require('../../assets/armory/shotguns/mastiff-off-the-grid.png'),
        enemy: require('../../assets/armory/shotguns/mastiff-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/shotguns/mastiff-out-for-blood.png'),
        surprise: require('../../assets/armory/shotguns/mastiff-surprise-party.png'),
        carnivale: require('../../assets/armory/shotguns/mastiff-carnivale.png'),
        solar: require('../../assets/armory/shotguns/mastiff-solar-flare.png'),
        wildlands: require('../../assets/armory/shotguns/mastiff-wildlands.png'),
        headgames: require('../../assets/armory/shotguns/mastiff-headgames.png'),
        paper: require('../../assets/armory/shotguns/mastiff-paper-trail.png'),
        icebreaker: require('../../assets/armory/shotguns/mastiff-icebreaker.png'),
        trident: require('../../assets/armory/shotguns/mastiff-trident.png'),
        tagged: require('../../assets/armory/shotguns/mastiff-tagged.png'),
        rave: require('../../assets/armory/shotguns/mastiff-warm-rave.png'),
        urban: require('../../assets/armory/shotguns/mastiff-urban-edge.png'),
        recluse: require('../../assets/armory/shotguns/mastiff-recluse.png'),
        wave: require('../../assets/armory/shotguns/mastiff-cold-wave.png'),
        afterimage: require('../../assets/armory/shotguns/mastiff-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/shotguns/mastiff-midnight.png'),
        cardinal: require('../../assets/armory/shotguns/mastiff-cardinal.png'),
        artic: require('../../assets/armory/shotguns/mastiff-artic.png'),
        sunfire: require('../../assets/armory/shotguns/mastiff-sunfire.png'),
        clearwater: require('../../assets/armory/shotguns/mastiff-clearwater.png'),
        flamingo: require('../../assets/armory/shotguns/mastiff-flamingo.png'),
        sandstorm: require('../../assets/armory/shotguns/mastiff-sandstorm.png'),
        rainforest: require('../../assets/armory/shotguns/mastiff-rainforest.png'),
        evergreen: require('../../assets/armory/shotguns/mastiff-evergreen.png'),
        orchid: require('../../assets/armory/shotguns/mastiff-orchid.png'),
        bengal: require('../../assets/armory/shotguns/mastiff-bengal.png'),
        yellowjacket: require('../../assets/armory/shotguns/mastiff-yellowjacket.png'),
        lagoon: require('../../assets/armory/shotguns/mastiff-lagoon.png'),
        clover: require('../../assets/armory/shotguns/mastiff-clover.png'),
        oceanic: require('../../assets/armory/shotguns/mastiff-oceanic.png'),
    },
    MOZAMBIQUE:{
        // Default Skin
        factory: require('../../assets/armory/shotguns/mozambique-factory-issue.png'),
        // Legendary Skins
        brotherOfTheBlade: require('../../assets/armory/shotguns/mozambique-brother-of-the-blade.png'),
        redAlert: require('../../assets/armory/shotguns/mozambique-red-alert.png'),
        impulseFire: require('../../assets/armory/shotguns/mozambique-impulse-fire.png'),
        honorGuard: require('../../assets/armory/shotguns/mozambique-honor-guard.png'),
        // Epic Skins
        storm: require('../../assets/armory/shotguns/mozambique-eye-of-the-storm.png'),
        trial: require('../../assets/armory/shotguns/mozambique-trial-by-fire.png'),
        honor: require('../../assets/armory/shotguns/mozambique-code-of-honor.png'),
        grid: require('../../assets/armory/shotguns/mozambique-off-the-grid.png'),
        enemy: require('../../assets/armory/shotguns/mozambique-break-the-enemy.png'),
        // Rare Skins
        generation: require('../../assets/armory/shotguns/mozambique-generation-x.png'),
        outback: require('../../assets/armory/shotguns/mozambique-outback.png'),
        sweet: require('../../assets/armory/shotguns/mozambique-sweet-16.png'),
        fusion: require('../../assets/armory/shotguns/mozambique-cold-fusion.png'),
        shattered: require('../../assets/armory/shotguns/mozambique-shattered.png'),
        stellar: require('../../assets/armory/shotguns/mozambique-stellar.png'),
        jungle: require('../../assets/armory/shotguns/mozambique-jungle-frenzy.png'),
        cloudburst: require('../../assets/armory/shotguns/mozambique-cloudburst.png'),
        yellow: require('../../assets/armory/shotguns/mozambique-yellow-snake.png'),
        skyrise: require('../../assets/armory/shotguns/mozambique-skyrise.png'),
        jester: require('../../assets/armory/shotguns/mozambique-jester.png'),
        derez: require('../../assets/armory/shotguns/mozambique-derez.png'),
        chaos: require('../../assets/armory/shotguns/mozambique-chaos-theory.png'),
        triumphant: require('../../assets/armory/shotguns/mozambique-triumphant-arch.png'),
        newmoon: require('../../assets/armory/shotguns/mozambique-new-moon.png'),
        // Common Skins
        midnight: require('../../assets/armory/shotguns/mozambique-midnight.png'),
        cardinal: require('../../assets/armory/shotguns/mozambique-cardinal.png'),
        artic: require('../../assets/armory/shotguns/mozambique-artic.png'),
        sunfire: require('../../assets/armory/shotguns/mozambique-sunfire.png'),
        clearwater: require('../../assets/armory/shotguns/mozambique-clearwater.png'),
        flamingo: require('../../assets/armory/shotguns/mozambique-flamingo.png'),
        sandstorm: require('../../assets/armory/shotguns/mozambique-sandstorm.png'),
        rainforest: require('../../assets/armory/shotguns/mozambique-rainforest.png'),
        evergreen: require('../../assets/armory/shotguns/mozambique-evergreen.png'),
        orchid: require('../../assets/armory/shotguns/mozambique-orchid.png'),
        bengal: require('../../assets/armory/shotguns/mozambique-bengal.png'),
        yellowjacket: require('../../assets/armory/shotguns/mozambique-yellowjacket.png'),
        lagoon: require('../../assets/armory/shotguns/mozambique-lagoon.png'),
        clover: require('../../assets/armory/shotguns/mozambique-clover.png'),
        oceanic: require('../../assets/armory/shotguns/mozambique-oceanic.png'),
    },
    // Pistol Skins
    P2020:{
        // Default Skin
        factory: require('../../assets/armory/pistols/p2020-factory-issue.png'),
        // Legendary Skins
        theNullifier: require('../../assets/armory/pistols/p2020-the-nullifier.png'),
        greenMamba: require('../../assets/armory/pistols/p2020-green-mamba.png'),
        ladyJustice: require('../../assets/armory/pistols/p2020-lady-justice.png'),
        deathsScepter: require('../../assets/armory/pistols/p2020-deaths-scepter.png'),
        // Epic Skins
        storm: require('../../assets/armory/pistols/p2020-eye-of-the-storm.png'),
        trial: require('../../assets/armory/pistols/p2020-trial-by-fire.png'),
        honor: require('../../assets/armory/pistols/p2020-code-of-honor.png'),
        grid: require('../../assets/armory/pistols/p2020-off-the-grid.png'),
        enemy: require('../../assets/armory/pistols/p2020-break-the-enemy.png'),
        // Rare Skins
        solstice: require('../../assets/armory/pistols/p2020-solstice.png'),
        warlord: require('../../assets/armory/pistols/p2020-warlord.png'),
        shockwave: require('../../assets/armory/pistols/p2020-shockwave.png'),
        fair: require('../../assets/armory/pistols/p2020-fun-fair.png'),
        rock: require('../../assets/armory/pistols/p2020-rock-bed.png'),
        kaleidoscope: require('../../assets/armory/pistols/p2020-kaleidoscope.png'),
        clockwork: require('../../assets/armory/pistols/p2020-clockwork.png'),
        slither: require('../../assets/armory/pistols/p2020-slither.png'),
        ladybug: require('../../assets/armory/pistols/p2020-ladybug.png'),
        envy: require('../../assets/armory/pistols/p2020-envy.png'),
        nile: require('../../assets/armory/pistols/p2020-nile.png'),
        coral: require('../../assets/armory/pistols/p2020-coral-reef.png'),
        morning: require('../../assets/armory/pistols/p2020-morning-dew.png'),
        cosmos: require('../../assets/armory/pistols/p2020-cosmos.png'),
        zeal: require('../../assets/armory/pistols/p2020-zeal.png'),
        // Common Skins
        midnight: require('../../assets/armory/pistols/p2020-midnight.png'),
        cardinal: require('../../assets/armory/pistols/p2020-cardinal.png'),
        artic: require('../../assets/armory/pistols/p2020-artic.png'),
        sunfire: require('../../assets/armory/pistols/p2020-sunfire.png'),
        clearwater: require('../../assets/armory/pistols/p2020-clearwater.png'),
        flamingo: require('../../assets/armory/pistols/p2020-flamingo.png'),
        sandstorm: require('../../assets/armory/pistols/p2020-sandstorm.png'),
        rainforest: require('../../assets/armory/pistols/p2020-rainforest.png'),
        evergreen: require('../../assets/armory/pistols/p2020-evergreen.png'),
        orchid: require('../../assets/armory/pistols/p2020-orchid.png'),
        bengal: require('../../assets/armory/pistols/p2020-bengal.png'),
        yellowjacket: require('../../assets/armory/pistols/p2020-yellowjacket.png'),
        lagoon: require('../../assets/armory/pistols/p2020-lagoon.png'),
        clover: require('../../assets/armory/pistols/p2020-clover.png'),
        oceanic: require('../../assets/armory/pistols/p2020-oceanic.png'),
    },
    RE45:{
        // Default Skin
        factory: require('../../assets/armory/pistols/re-45-factory-issue.png'),
        // Legendary Skins
        thePride: require('../../assets/armory/pistols/re-45-the-pride.png'),
        thePredator: require('../../assets/armory/pistols/re-45-the-predator.png'),
        freezingPoint: require('../../assets/armory/pistols/re-45-freezing-point.png'),
        theRegulator: require('../../assets/armory/pistols/re-45-the-regulator.png'),
        // Epic Skins
        storm: require('../../assets/armory/pistols/re-45-eye-of-the-storm.png'),
        trial: require('../../assets/armory/pistols/re-45-trial-by-fire.png'),
        honor: require('../../assets/armory/pistols/re-45-code-of-honor.png'),
        grid: require('../../assets/armory/pistols/re-45-off-the-grid.png'),
        enemy: require('../../assets/armory/pistols/re-45-break-the-enemy.png'),
        // Rare Skins
        blood: require('../../assets/armory/pistols/re-45-out-for-blood.png'),
        surprise: require('../../assets/armory/pistols/re-45-surprise-party.png'),
        carnivale: require('../../assets/armory/pistols/re-45-carnivale.png'),
        solar: require('../../assets/armory/pistols/re-45-solar-flare.png'),
        wildlands: require('../../assets/armory/pistols/re-45-wildlands.png'),
        headgames: require('../../assets/armory/pistols/re-45-headgames.png'),
        paper: require('../../assets/armory/pistols/re-45-paper-trail.png'),
        icebreaker: require('../../assets/armory/pistols/re-45-icebreaker.png'),
        trident: require('../../assets/armory/pistols/re-45-trident.png'),
        tagged: require('../../assets/armory/pistols/re-45-tagged.png'),
        rave: require('../../assets/armory/pistols/re-45-warm-rave.png'),
        urban: require('../../assets/armory/pistols/re-45-urban-edge.png'),
        recluse: require('../../assets/armory/pistols/re-45-recluse.png'),
        wave: require('../../assets/armory/pistols/re-45-cold-wave.png'),
        afterimage: require('../../assets/armory/pistols/re-45-digital-afterimage.png'),
        // Common Skins
        midnight: require('../../assets/armory/pistols/re-45-midnight.png'),
        cardinal: require('../../assets/armory/pistols/re-45-cardinal.png'),
        artic: require('../../assets/armory/pistols/re-45-artic.png'),
        sunfire: require('../../assets/armory/pistols/re-45-sunfire.png'),
        clearwater: require('../../assets/armory/pistols/re-45-clearwater.png'),
        flamingo: require('../../assets/armory/pistols/re-45-flamingo.png'),
        sandstorm: require('../../assets/armory/pistols/re-45-sandstorm.png'),
        rainforest: require('../../assets/armory/pistols/re-45-rainforest.png'),
        evergreen: require('../../assets/armory/pistols/re-45-evergreen.png'),
        orchid: require('../../assets/armory/pistols/re-45-orchid.png'),
        bengal: require('../../assets/armory/pistols/re-45-bengal.png'),
        yellowjacket: require('../../assets/armory/pistols/re-45-yellowjacket.png'),
        lagoon: require('../../assets/armory/pistols/re-45-lagoon.png'),
        clover: require('../../assets/armory/pistols/re-45-clover.png'),
        oceanic: require('../../assets/armory/pistols/re-45-oceanic.png'),
    },
    WINGMAN:{
        // Default Skin
        factory: require('../../assets/armory/pistols/wingman-factory-issue.png'),
        // Legendary Skins
        deadHeat: require('../../assets/armory/pistols/wingman-dead-heat.png'),
        thermalRise: require('../../assets/armory/pistols/wingman-thermal-rise.png'),
        theDeathRay: require('../../assets/armory/pistols/wingman-the-death-ray.png'),
        mercilessWing: require('../../assets/armory/pistols/wingman-merciless-wing.png'),
        // Epic Skins
        storm: require('../../assets/armory/pistols/wingman-eye-of-the-storm.png'),
        trial: require('../../assets/armory/pistols/wingman-trial-by-fire.png'),
        honor: require('../../assets/armory/pistols/wingman-code-of-honor.png'),
        grid: require('../../assets/armory/pistols/wingman-off-the-grid.png'),
        enemy: require('../../assets/armory/pistols/wingman-break-the-enemy.png'),
        // Rare Skins
        generation: require('../../assets/armory/pistols/wingman-generation-x.png'),
        outback: require('../../assets/armory/pistols/wingman-outback.png'),
        sweet: require('../../assets/armory/pistols/wingman-sweet-16.png'),
        fusion: require('../../assets/armory/pistols/wingman-cold-fusion.png'),
        shattered: require('../../assets/armory/pistols/wingman-shattered.png'),
        stellar: require('../../assets/armory/pistols/wingman-stellar.png'),
        jungle: require('../../assets/armory/pistols/wingman-jungle-frenzy.png'),
        cloudburst: require('../../assets/armory/pistols/wingman-cloudburst.png'),
        yellow: require('../../assets/armory/pistols/wingman-yellow-snake.png'),
        skyrise: require('../../assets/armory/pistols/wingman-skyrise.png'),
        jester: require('../../assets/armory/pistols/wingman-jester.png'),
        derez: require('../../assets/armory/pistols/wingman-derez.png'),
        chaos: require('../../assets/armory/pistols/wingman-chaos-theory.png'),
        triumphant: require('../../assets/armory/pistols/wingman-triumphant-arch.png'),
        newmoon: require('../../assets/armory/pistols/wingman-new-moon.png'),
        // Common Skins
        midnight: require('../../assets/armory/pistols/wingman-midnight.png'),
        cardinal: require('../../assets/armory/pistols/wingman-cardinal.png'),
        artic: require('../../assets/armory/pistols/wingman-artic.png'),
        sunfire: require('../../assets/armory/pistols/wingman-sunfire.png'),
        clearwater: require('../../assets/armory/pistols/wingman-clearwater.png'),
        flamingo: require('../../assets/armory/pistols/wingman-flamingo.png'),
        sandstorm: require('../../assets/armory/pistols/wingman-sandstorm.png'),
        rainforest: require('../../assets/armory/pistols/wingman-rainforest.png'),
        evergreen: require('../../assets/armory/pistols/wingman-evergreen.png'),
        orchid: require('../../assets/armory/pistols/wingman-orchid.png'),
        bengal: require('../../assets/armory/pistols/wingman-bengal.png'),
        yellowjacket: require('../../assets/armory/pistols/wingman-yellowjacket.png'),
        lagoon: require('../../assets/armory/pistols/wingman-lagoon.png'),
        clover: require('../../assets/armory/pistols/wingman-clover.png'),
        oceanic: require('../../assets/armory/pistols/wingman-oceanic.png'),
    }
};

export default weaponsImages;